apiVersion: v1
kind: Service
metadata:
  name: voting-service
  label:
    name: voting-service
    app: demo-voting-app
  spec:
    ports:
    - port: 80
      targetPort: 80
    type: LoadBalancer
    selector:
      name: voting-app-pod
      app: demo-voting-pod